# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"

before_install:
  - curl -L https://github.com/coreos/etcd/releases/download/v3.0.4/etcd-v3.0.4-linux-amd64.tar.gz -o etcd-v3.0.4-linux-amd64.tar.gz
  - tar xzvf etcd-v3.0.4-linux-amd64.tar.gz
  - cd etcd-v3.0.4-linux-amd64
  - ./etcd > /dev/null &
  - cd ..
  - sleep 10

install:
  - pip install -r requirements.txt
  - pip install coverage==3.7.1 coveralls

# command to run tests, e.g. python setup.py test
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then PYTHONWARNINGS=i coverage run --include "layeredconfig/*py" -m unittest2 discover tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then PYTHONWARNINGS=i coverage run --include "layeredconfig/*py" -m unittest discover tests; fi
after_success:
  - coveralls
